ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER "scott" IDENTIFIED BY "tiger";

GRANT CONNECT, RESOURCE, DBA TO "INHO3849" ;


GRANT SELECT ON SYS.v_$session  TO "INHO3849";
GRANT SELECT ON SYS.v_$sql  TO "INHO3849";
GRANT ALTER SESSION TO "INHO3849"
;
SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'INHO3849'
;
SELECT * FROM USER_SYS_PRIVS;
;
GRANT CREATE ANY TABLE TO "INHO3849"
;
SQL Error [2421] [42000]: ORA-02421: 누락 혹은 부당한 스키마 권한 식별자

  Error : 2421, Position : 33, SQL = ALTER SESSION SET CURRENT_SCHEMA=PUBLIC, Original SQL = ALTER SESSION SET CURRENT_SCHEMA=PUBLIC, Error Message = ORA-02421: 누락 혹은 부당한 스키마 권한 식별자



;
SELECT *
  FROM v_$session
  
  ;

  

  